### ISSUE TITLE
"cordova plugin add cordova-plugin-sim" fails to execute

### ISSUE THREAD

**Issue by JohnnySheffield** [pbakondy/cordova-plugin-sim#2]
Here's log dump of what i get when i try to execute:

```
$ cordova plugin add cordova-plugin-sim

Fetching plugin "cordova-plugin-sim" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-sim
npm http 404 http://registry.cordova.io/cordova-plugin-sim
Error: 404 Not Found: cordova-plugin-sim
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

Can you provide some info am i in error, or something is not set up correctly on the cordova plugin registry?

**Comment by pbakondy** [comment]
It works for me:

```
$ cordova plugin add cordova-plugin-sim
Fetching plugin "cordova-plugin-sim" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-sim
npm http 200 https://registry.npmjs.org/cordova-plugin-sim
Installing "cordova-plugin-sim" for ios
$ ionic -v
1.5.0
$ cordova -v
5.0.0
```

Please try with latest Cordova CLI version.

**Comment by JohnnySheffield** [comment]
Thank you for helping out. I was running cordova 4.2.0. ,with cordova 5.0.0. everything is working as expected.

Closing.

Cheers!
